package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Dark Palette (Obsidian Base)
val DarkBackground = Color(0xFF0A0E17)
val DarkSurfaceLowest = Color(0xFF0E1320)
val DarkSurfaceLow = Color(0xFF131A29)
val DarkSurfaceContainer = Color(0xFF192239)
val DarkSurfaceHigh = Color(0xFF243049)
val DarkSurfaceHighest = Color(0xFF28354D)
val DarkOutline = Color(0xFF3B4861)
val DarkOutlineVariant = Color(0xFF2D3748)
val DarkOnSurface = Color(0xFFF1F5F9)
val DarkOnSurfaceVariant = Color(0xFF94A3B8)
val DarkPrimary = Color(0xFF38BDF8)
val DarkOnPrimary = Color(0xFF001F2B)
val DarkPrimaryContainer = Color(0xFF0B4A6F)
val DarkOnPrimaryContainer = Color(0xFFBAE6FD)
val DarkSecondary = Color(0xFF9EBAE6)
val DarkOnSecondary = Color(0xFF0F2C4E)
val DarkSecondaryContainer = Color(0xFF1D406E)
val DarkOnSecondaryContainer = Color(0xFFAFCBEE)
val DarkTertiary = Color(0xFFFB923C)
val DarkOnTertiary = Color(0xFF2B1700)
val DarkTertiaryContainer = Color(0xFF5F3400)
val DarkOnTertiaryContainer = Color(0xFFFFDDC0)
val DarkError = Color(0xFFF43F5E)
val DarkOnError = Color(0xFF3F000E)
val DarkErrorContainer = Color(0xFF70001D)
val DarkOnErrorContainer = Color(0xFFFFD9DF)

// Light Palette (Cool Slate Canvas)
val LightBackground = Color(0xFFEDF2F7)
val LightSurfaceLowest = Color(0xFFFFFFFF)
val LightSurfaceLow = Color(0xFFF8FAFC)
val LightSurfaceContainer = Color(0xFFF1F5F9)
val LightSurfaceHigh = Color(0xFFE2E8F0)
val LightSurfaceHighest = Color(0xFFCBD5E1)
val LightOutline = Color(0xFF8B98A5)
val LightOutlineVariant = Color(0xFFCBD5E1)
val LightOnSurface = Color(0xFF0F172A)
val LightOnSurfaceVariant = Color(0xFF475569)
val LightPrimary = Color(0xFF0284C7)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBAE6FD)
val LightOnPrimaryContainer = Color(0xFF00354E)
val LightSecondary = Color(0xFF3F6490)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCEE0F5)
val LightOnSecondaryContainer = Color(0xFF0B2848)
val LightTertiary = Color(0xFFD97706)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDDC0)
val LightOnTertiaryContainer = Color(0xFF3C1E00)
val LightError = Color(0xFFE11D48)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFD9DF)
val LightOnErrorContainer = Color(0xFF410011)

// Semantic status colors
val SuccessDark = Color(0xFF10B981)
val SuccessLight = Color(0xFF059669)
val WarningDark = Color(0xFFFB923C)
val WarningLight = Color(0xFFD97706)
val CategoryDark = Color(0xFFA78BFA)
val CategoryLight = Color(0xFF7C3AED)

val DarkTintedShadow = Color(0x66000000)
val LightTintedShadow = Color(0x18000000)
